SET(EP_USD "USD")
  ExternalProject_Add (
    ${EP_USD}

    PREFIX        ${EP_USD}
    DOWNLOAD_DIR  ${EP_USD}
    STAMP_DIR     ${EP_USD}/stamp
    SOURCE_DIR    ${EP_USD}/source
    BINARY_DIR    ${EP_USD}/build
    GIT_REPOSITORY ${SUPERBUILD_USD_URL}
    GIT_TAG       ${SUPERBUILD_USD_VERSION}
    GIT_SHALLOW   OFF

    LIST_SEPARATOR | # Use the alternate list separator
    CMAKE_ARGS
      -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
      -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
      -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_INSTALL_PREFIX}
      -DBUILD_ALL_DEPS=OFF
      -DUSE_PYTHON=${USE_PYTHON}
      -DUSE_PYTHON2=OFF
      -DBUILD_TBB=ON
      -DBUILD_BOOST=ON
      -DBUILD_GLEW=OFF
      -DBUILD_PTEX=ON
      -DBUILD_OPENEXR=ON
      -DPXR_ENABLE_PTEX_SUPPORT=ON
      -DBUILD_OPENSUBDIV=ON
      -DBUILD_HDF5=ON
      -DBUILD_OPENIMAGEIO=ON
      -DPXR_BUILD_OPENIMAGEIO_PLUGIN=ON
    INSTALL_COMMAND ""
    BUILD_ALWAYS OFF
  )

  ExternalProject_Add_StepDependencies(${EP_USD}
        configure ${USD_DEPENDENCIES}
      )
