##
## OpenSubdiv
##

set(OPENSUBDIV_ARGS
    -DNO_DOC=ON
    -DNO_OMP=ON
    -DNO_EXAMPLES=ON
    -DNO_CUDA=ON
    -DNO_TUTORIALS=ON
    -DNO_REGRESSION=ON
    -DNO_OPENCL=ON
    -DNO_TESTS=ON
    -DNO_GLEW=ON
    -DNO_GLFW=ON
    -DNO_PTEX=ON
    -DNO_TBB=ON
    -DTBB_LOCATION=${CMAKE_INSTALL_PREFIX}
)

#set(OPENSUBDIV_DEPENDENCIES Ptex)

if(BUILD_TBB)
    set(OPENSUBDIV_ARGS
        ${OPENSUBDIV_ARGS}
        -DTBB_LOCATION=${CMAKE_INSTALL_PREFIX}
    )
    set(OPENSUBDIV_DEPENDENCIES
        ${PENSUBDIV_DEPENDENCIES}
        tbb
    )
endif()

build_component(
  NAME OpenSubdiv
  VERSION "v3_5_0"
  URL https://github.com/PixarAnimationStudios/OpenSubdiv
  BUILD_ARGS ${OPENSUBDIV_ARGS}
  DEPENDS_ON ${OPENSUBDIV_DEPENDENCIES}
)